### PR TITLE
Make cipher suite configurable

### PR DESCRIPTION
**Pull request by mynameistroy**
Hi Ulrich,

I needed to make the cipher suite in your library configurable to build on some Solaris and AIX platforms. I wanted to give back if were interested in merging it into the master.

Thanks for such a handy project!
_Troy

### CODE REVIEW

**Comment by utelle** [comment]
Hi Troy,

> I needed to make the cipher suite in your library configurable to build on some Solaris and AIX platforms.

Did you experience any specific compile/build problems on Solaris and AIX? If yes, which ones? Maybe it would be possible to overcome them.

> I wanted to give back if were interested in merging it into the master.

I think it is definitely a useful feature to build the library in such a way that only a certain selection of ciphers is supported at runtime. Not all applications always need support for all ciphers.

That is, I will take a closer look at your PR as soon as possible. However, please allow some time for this to happen, because I currently have only limited access to my development environment due to personal affairs.

**Comment by mynameistroy** [comment]
So for both platforms it complained here for the endian.h
https://github.com/utelle/wxsqlite3/blob/7cc06ea086501af20c0c01e64fa0ccf3d1a1e470/sqlite3secure/src/fastpbkdf2.c#L20

Also AIX didn't like this either 
https://github.com/utelle/wxsqlite3/blob/7cc06ea086501af20c0c01e64fa0ccf3d1a1e470/sqlite3secure/src/chacha20poly1305.c#L241

Now I would imagine some work around the preprocessor flags might fix it up but I figured controlling the cipher suite configuration was also handy. Since I only needed the AES algorithms present for my needs.

As for the timing no worries, I just wanted to give you the option to merge it back if it happened to be useful.

**Comment by utelle** [comment]
> So for both platforms it complained here for the `endian.h` (in line 20 of `fastpbkdf2.c`)

I assume _complaining_ means that header file is missing. What happens, if you simply remove the include? It seems that only GNUC needs it. Could you please check this out?

> Also AIX didn't like this either (in line 241 of `chacha20poly1305.c`)

Line 241 is just the start of a multi-line C comment. No idea, why any compiler should complain about a comment! However, the code following line 241 specifies how to generate random bytes. Maybe AIX doesn't like some of that code. Since I don't have access to an AIX system, I don't know whether AIX provides other means of generating random bytes.

Regarding your PR I have a few remarks:

1) `sqlite3secure/configure.ac`
In `configure.ac` (root folder) you additionally check that the selected default cipher is really supported, not omitted by a `without` option. IMHO this should be done here, too.
Additionally, it might be good to check that not **all** ciphers were disabled, because in that case `SQLITE_HAS_CODEC` should simply be undefined.

2) `samples/minimal.cpp`
IMHO the sample application should be adjusted as well, so that only those cipher related tests are performed that use supported ciphers. However, this can be done later on.

3) Independent selection of supported ciphers
Currently your modifications to `codec.c` allows to deselect the SQLCipher cipher, but it will be still available in the global codec parameter table (line 1566 ff). This can lead to problems.

That is, before the PR can be accepted a few further adjustments at least to `codec.c` would have to be done.

**Comment by mynameistroy** [comment]
Yes my apologies for the poor communication on that! Thankfully you did get what I meant by the links to the source.

I agree that it would be better to properly solve the issue so that the ciphers build on those platforms. In my case though I have a lot of both AIX and Solaris platforms to deal with and this was the quickest and easiest solution for me. I would like to fix it up properly later should have the time and the access to the environments.

I addressed comments #1 and #3 and agreed that #2 should be done but can come later.

Let me know if there is anything else needed.

**Comment by utelle** [comment]
> I agree that it would be better to properly solve the issue so that the ciphers build on those platforms.

Absolutely. And hopefully that won't require too much effort.

> In my case though I have a lot of both AIX and Solaris platforms to deal with and this was the quickest and easiest solution for me.

I fully understand that. However, from my point of view it is of course preferrable to get the code to compile and run under those platforms, too.

> I would like to fix it up properly later should have the time and the access to the environments.

I'd really appreciate if you can dedicate some time to adjust the code for those platforms.

> I addressed comments #1 and #3 and agreed that #2 should be done but can come later.
> Let me know if there is anything else needed.

I'll check the modifications over the weekend and will let you know, if further adjustments are necessary.

**Comment by utelle** [comment]
AFAICT no further adjustments seem to be necessary at the moment. And since the default behaviour - namely, including support for **all** ciphers - does not change, I will accept your PR.

Let's then see what other users of _wxSQLite3_ have to say about this new configuration option.

**Comment by mynameistroy** [comment]
Thanks Ulrich! Happy to have been able to give back, hopefully more will come in the future.

**Pull request merged**
