### PR TITLE
fix some bugs?

### PR DESCRIPTION
**Pull request by liaoxuewei**
* fixed bug in calling getentropy under Mac OS 10.11
https://github.com/utelle/wxsqlite3/issues/53
Reference:
https://github.com/pyca/cryptography/pull/3841

* fix compile error in android platform
* fix bug: attach database twice will error use non-default encryption algorithm

### CODE REVIEW

**Comment by utelle** [comment]
1) `getentropy` issue
I intend to discuss this with @resilar, too, because I suspect that **sqleet** might be affected as well.

2) compile error on Android
I would prefer to simply `#undef B0` instead of introducing a new definition. Even better would be to avoid changing the source file `shathree.c` at all, since `shathree.c` is an unmodified file from the SQLite distribution. And I see a good chance that this can be accomplished by simply including `shathree.c` earlier in `sqlite3secure.c`. Maybe right after `#include sqlite3.c`. If that still results in a compile error, then before `#include sqlite3.c`. Could you test this?

3) attach database issue
I will check the issue. I have to verify that your fix doesn't break anything else. 

Please allow some time to check your PR.

**Comment by utelle** [comment]
Regarding the compile error on Android I made a few tests myself.

Moving the include point of `shathree.c` doesn't help. Therefore I sent a message to the SQLite mailing list. Let's see whether we get a response.

I definitely don't want to apply any changes to `shathree.c`. If the SQLite developers decide to not change the source code of the SHA3 extension to avoid the name clash, I would prefer to handle the issue within `sqlite3secure.c` by adding preprocessor checks before including `shathree.c`.

**Comment by utelle** [comment]
Commit 86ac88c801b9f3cfd82a9301be0021e16957d1dc fixes the compile error on Android.

Unfortunately I had not spotted that the source file `shathree.c` had been already adjusted by the SQLite developers quite long ago. With the latest version the compile problem should be gone.

**Comment by utelle** [comment]
Regarding your issue _**attach database twice will error use non-default encryption algorithm**_ I need additional information. Please describe the steps you took to open your database and then attach another database twice. That is, which calls did you perform to set the parameters for the encryption extension, what did you expect, and what happened instead.

From my point of view applying your patch would break the **wxSQLite3 concept** of maintaining 2 sets of encryption parameters, the _transient set_ and the _permanent set_. The _transient set_ is used exactly once for setting up the next cipher scheme, while the _permanent set_ is used throughout the lifetime of a database connection, unless explicitly overwritten by a modified _transient set_.

**Comment by liaoxuewei** [comment]
Thank you for handling and responding. I think the Android problem can be solved. This problem is mainly caused by repeated definitions. I'll test it later.
With regard to the problem that attach database will fail twice, my steps are as follows:
1. Open a database with an non-default encryption algorithm(ex. aes128cbc, default is chacha20) as the main database;
2. Run scripts on data connections like:
        execSql("ATTACH DATABASE 'xx1.db' AS M key '123'");
        execSql("ATTACH DATABASE 'xx2.db' AS S key '123'");
It will fail while run ATTACH DATABASE 'xx2.db'....
This problem is not tested in the latest version, but I think this part of the code has not been modified, so I think it should be problematic.

**Comment by utelle** [comment]
> I think the Android problem can be solved. This problem is mainly caused by repeated definitions. I'll test it later.

The problem should already be solved by replacing `shathree.c` with the latest source code version in commit 86ac88c801b9f3cfd82a9301be0021e16957d1dc.

> With regard to the problem that attach database will fail twice, my steps are as follows:
> 
> 1. Open a database with an non-default encryption algorithm(ex. aes128cbc, default is chacha20) as the main database;

How do you select the non-default cipher scheme?

> 2. Run scripts on data connections like:
>        execSql("ATTACH DATABASE 'xx1.db' AS M key '123'");
>        execSql("ATTACH DATABASE 'xx2.db' AS S key '123'");
>        It will fail while run ATTACH DATABASE 'xx2.db'....

I assume that your `main.db` as well as `xx1.db` and `xx2.db` should use the same non-default cipher scheme. If you want to use the same non-default cipher scheme for all databases, you have to change the default for your main database connection. For example, by executing
```SQL
SELECT wxsqlite3_config('default:cipher', 'aes128cbc');
```
before using
```SQL
PRAGMA key='...';
```
for the main database. Thereafter cipher scheme `aes128cbc` should be used for all attached databases automatically.

**Comment by liaoxuewei** [comment]
First, you're right. all databases are same cipher scheme, but not non-default one.
Maybe the method you mentioned can solve it, but I need to verify it again, but do I feel that the algorithm is a bit wrong?

static int
GetCipherType(sqlite3* db)
{
  CodecParameter* codecParams = (db != NULL) ? GetCodecParams(db) : codecParameterTable;
  CipherParams* cipherParamTable = (codecParams != NULL) ? codecParams[0].m_params : commonParams;
  int cipherType = CODEC_TYPE;
  CipherParams* cipher = cipherParamTable;
  for (; strlen(cipher->m_name) > 0; ++cipher)
  {
    if (sqlite3_stricmp("cipher", cipher->m_name) == 0) break;
  }
  if (strlen(cipher->m_name) > 0)
  {
    cipherType = cipher->m_value;
    //cipher->m_value = cipher->m_default; // If the codecParams is NULL, commonParams will changed, is that what you expected?
  }
  return cipherType;
}

**Comment by utelle** [comment]
> First, you're right. all databases are same cipher scheme, but not non-default one.

Hm, what are you trying to tell? "**not non-default**" translates to "**default**". However, you stated earlier that you are using **aes128cbc** ... and that's currently a _**non-default**_ cipher, because since version 4.0.0 of wxSQLite3 the default cipher is **ChaCha20**.

If you know that your application will always use **aes128cbc**, then I would recommend that you compile the wxSQLite3 code preselecting the **aes128cbc** cipher by defining the preprocessor symbol `CODEC_TYPE=CODEC_TYPE_AES128`.

> Maybe the method you mentioned can solve it, but I need to verify it again, but do I feel that the algorithm is a bit wrong?

In file `codec.h` you find the following lines 
```C
#define CODEC_TYPE_DEFAULT CODEC_TYPE_CHACHA20

#ifndef CODEC_TYPE
#define CODEC_TYPE CODEC_TYPE_DEFAULT
#endif
```
That is, if no specific cipher type was defined, the cipher type **ChaCha20** will be selected as the (compile time) default. This can be changed as mentioned above.

Internally, function `GetCipherType` is never called with a NULL pointer for the `db` parameter. And since it is a _static_ function it can't be called from the outside (unless you modified the code).

Initially I had intended to offer a way to modify the compile time defaults at runtime by calling function `wxsqlite3_config` with a NULL pointer for the `db` parameter. However, in the end I decided against this feature. The current implementation just allows to **query** the compile time defaults in this way, but not to **modify** them.

Each database connection (`sqlite3` instance) holds a copy of the compile time default settings for all supported ciphers. Changing the defaults (per database connection) can be done using the `default:` prefix for the parameter names.

**Comment by liaoxuewei** [comment]
Maybe my description is not very clear. Let me redefine it and discuss it again.
1. The scenario I'm talking about is set CODEC_TYPE = CODEC_TYPE_CHACHA20, but I want to dynamically specify the AES128 encryption algorithm.
2. As I understand it, when attaching a database, the encryption algorithm of other databases must be the same as that of the main database. Because the script attached to the database does not specify an encryption algorithm.
3. Before I modify the code, I do two attaching database operations. The second attaching database will make an error, but it is normal to Modified code.
4. I didn't understand the purpose of cipher->m_value = cipher->m_default. I feel like there seems to be a problem with that piece of code.

**Comment by utelle** [comment]
> 1. The scenario I'm talking about is set CODEC_TYPE = CODEC_TYPE_CHACHA20, but I want to dynamically specify the AES128 encryption algorithm.

Ok, this means that the **ChaCha20** cipher will be used as the **default** encryption scheme unless you explicitly change the encryption scheme on opening or attaching a database.

> 2. As I understand it, when attaching a database, the encryption algorithm of other databases must be the same as that of the main database. Because the script attached to the database does not specify an encryption algorithm.

No, each database you open or attach can have a different encryption scheme. However, using the same encryption scheme for all databases will most likely be the common case.

If an attached database uses a different encryption scheme than the main database, it is required to explicitly specify the encryption scheme for the database being attached. There are 2 methods, how this can be accomplished:

1) Use URI parameters to specify the encryption scheme.
 Example: 
```SQL
ATTACH DATABASE 'file:databasefile1.db3?cipher=aes128cbc' AS attached1 KEY 'passphrase';
```

2) Use SQL function to specify the encryption scheme.
 Example:
```SQL
SELECT wxsqlite3_config('cipher','aes128cbc');
ATTACH DATABASE 'databasefile1.db3' AS attached1 KEY 'passphrase';
```

> 3. Before I modify the code, I do two attaching database operations. The second attaching database will make an error, but it is normal to Modified code.

If you want to attach 2 (or more) database files which are encrypted with the **aes128cbc** encryption scheme, you have again 2 ways to accomplish this:

1) Specify the **cipher** parameter for each attached database file: 
```SQL
ATTACH DATABASE 'file:databasefile1.db3?cipher=aes128cbc' AS attached1 KEY 'passphrase1';
ATTACH DATABASE 'file:databasefile2.db3?cipher=aes128cbc' AS attached2 KEY 'passphrase2';
```

2) Change the default encryption scheme before attaching the database files:
```SQL
SELECT wxsqlite3_config('default:cipher','aes128cbc');
ATTACH DATABASE 'databasefile1.db3' AS attached1 KEY 'passphrase1';
ATTACH DATABASE 'databasefile2.db3' AS attached2 KEY 'passphrase2';
```

> 4. I didn't understand the purpose of cipher->m_value = cipher->m_default. I feel like there seems to be a problem with that piece of code.

No, there is definitely no problem with that code. It does what it is meant to do.

I assume you tried the following:
```SQL
SELECT wxsqlite3_config('cipher','aes128cbc');
ATTACH DATABASE 'databasefile1.db3' AS attached1 KEY 'passphrase1';
ATTACH DATABASE 'databasefile2.db3' AS attached2 KEY 'passphrase2';
```
If both attached database files are encrypted with **aes128cbc**, then accessing the second database will fail, because the default encryption scheme is reset to **ChaCha20** after the first database has been attached - however, this is the intended and documented behaviour. 

If you don't want to change the default encryption scheme, then you have to repeat the selection of the encryption scheme as follows:
```SQL
SELECT wxsqlite3_config('cipher','aes128cbc');
ATTACH DATABASE 'databasefile1.db3' AS attached1 KEY 'passphrase1';
SELECT wxsqlite3_config('cipher','aes128cbc');
ATTACH DATABASE 'databasefile2.db3' AS attached2 KEY 'passphrase2';
```
Alternatively you could change the default encryption scheme as shown previously.

Your code change breaks the intended and documented behaviour of the encryption extension. Therefore I will not apply it.

**Comment by utelle** [comment]
I'd like to add that if your main database **_and_** the databases you attach are all encrypted with **aes128cbc**, then your use case can be simplified:

1) Open your main database using URI parameters: `'file:maindatabase.db3?cipher=aes128cbc'`.
 **Note**: This will implicitly set the default encryption scheme to **aes128cbc**.
2) Attach your other database files which are encrypted with **aes128cbc** using the default encryption scheme (which is now **aes128cbc**):
```SQL
ATTACH DATABASE 'databasefile1.db3' AS attached1 KEY 'passphrase1';
ATTACH DATABASE 'databasefile2.db3' AS attached2 KEY 'passphrase2';
```

**Comment by liaoxuewei** [comment]
I tested it according to your method. All platforms have worked very well. Thank you very much.

**Pull request closed without merging**
